image: "k8r.eu/justjanne/android-sdk:36-594c2cc3"

cache:
  key: "$CI_PROJECT_NAME"
  paths:
    - ".gradle/caches"

before_script:
  - "mkdir -p $(pwd)/.gradle"
  - "export GRADLE_USER_HOME=$(pwd)/.gradle"
  - "echo $SIGNING_KEYSTORE | base64 -d > /root/signing.keystore"
  - "echo $SIGNING_PROPERTIES | base64 -d > signing.properties"
  - "chmod +x ./gradlew"

stages:
  - "test"
  - "release"

test:
  stage: "test"
  script:
    - "./gradlew assembleRelease bundleRelease -x lintRelease -x lintVitalRelease"
    - "cp */build/outputs/apk/release/*.apk ."
    - "cp */build/outputs/bundle/release/*.aab ."
    - "./gradlew check -x connectedCheck"
  artifacts:
    paths:
      - "*.apk"
      - "*.aab"
      - "*/build/test-results/**/TEST-*.xml"
      - "*/build/reports/*.xml"
    reports:
      junit:
        - "*/build/test-results/**/TEST-*.xml"
        - "*/build/reports/*.xml"

deploy-local:
  stage: "release"
  image: "quay.io/minio/mc:RELEASE.2025-08-13T08-35-41Z"
  cache: { }
  dependencies:
    - "test"
  script:
    - "mc cp $S3_CONFIG /root/.mc/config.json"
    - "mc find $CI_PROJECT_DIR --name '*.apk' --exec 'mc cp --preserve {} s3/releases/voctotv/'"
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: on_success
